<?php
namespace Puja\Bob\Module\System\Controller;
use Puja\Bob\Module\System\Model\DataGrid;
class LanguageController extends \Puja\Bob\Controller\DataGrid\DataGridAbstract
{
    protected $isGridDnD = true;
    protected function getModel()
    {
        return \Puja\Bob\Model\Configure\Language::getInstance();
    }

    protected function getDataGridModel()
    {
        return DataGrid\Language::getInstance($this);
    }

    public function updateAction()
    {
        if ($_POST) {
            return parent::updateAction(); // TODO: Change the autogenerated stub

        }
        $data = array();
        if ($this->getParam('pkid')) {
            $data['entity'] = $this->getModel()->getByPkId($this->getParam('pkid'));
        }
        $this->render('System/Update/Language.tpl', $data);
    }
}