<?php
namespace Puja\Bob\Module\Html\Controller;
use Puja\Bob\Module\Html\Model\Html;
use Puja\Configure\Configure;

class IndexController extends \Puja\Bob\Module\Entity\Controller\IndexController
{
    protected function getModel()
    {
        return null;
    }

    protected function getGridFields()
    {
        return array(
            'name' => array('title' => 'Name', 'formatter' => 'name', 'width' => '50%', 'resizable' => true, 'sortable' => true),
            'addtime' => array('title' => 'Created At', 'align' => 'center', 'width' => '120', 'sortable' => true),
        );
    }

    public function beforeLoadAction()
    {
        $this->redirect('./');
        parent::beforeLoadAction(); // TODO: Change the autogenerated stub
    }
}